# Generated by Django 4.2.5 on 2023-10-08 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+237690657643",
                        max_length=30,
                        region=None,
                        verbose_name="Phone_number",
                    ),
                ),
                (
                    "about_me",
                    models.TextField(
                        default=" Say something about you", verbose_name="about me"
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="License"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        upload_to="images/default.png", verbose_name="Profile photo"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=30,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "is_buyer",
                    models.BooleanField(
                        default=False, help_text="are you a buyer", verbose_name="Buyer"
                    ),
                ),
                (
                    "is_seller",
                    models.BooleanField(
                        default=False,
                        help_text="are you a seller",
                        verbose_name="seller",
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(
                        default=False, help_text="are you a agent", verbose_name="agent"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="CM", max_length=255, verbose_name="country name"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default="Douala", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "top_agent",
                    models.BooleanField(default=False, verbose_name="Top Agent"),
                ),
                (
                    "ratings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "num_reviews",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Number of reviews",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
